#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════
   Sitemap builder — `npm run build:sitemap`

   sitemap.xml was hand-maintained, which meant it listed pages that no
   longer existed, carried lastmod dates frozen at 2026-03-31, and — the
   expensive part — did not list pages that did exist. Adding 41 more
   pages by hand was not going to go any better.

   So the sitemap is derived: every git-tracked HTML page that is not
   noindexed, at the URL its own <link rel="canonical"> declares, with
   lastmod taken from the file's last commit date.

   Priority is a hint, not a ranking lever. The scale here is simply:
   home > the two hub pages > everything else > redirect stubs.
   ═══════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const ORIGIN = 'https://greenborder.org';

// Pages that exist for machines or errors, not for searchers.
const EXCLUDE = new Set(['404.html']);

const PRIORITY = [
  [/^https:\/\/greenborder\.org\/$/, 1.0, 'weekly'],
  [/\/dispensaries\/$/, 0.95, 'weekly'],
  [/\/el-paso-cannabis\.html$/, 0.95, 'weekly'],
  [/\/dispensaries\//, 0.8, 'weekly'],
  [/\/news\.html$/, 0.9, 'daily'],
  [/\/education\//, 0.7, 'monthly'],
  [/\/articles\//, 0.6, 'monthly'],
  [/\/data\.html$/, 0.8, 'weekly'],
];

const rank = (url) => {
  for (const [re, priority, changefreq] of PRIORITY)
    if (re.test(url)) return { priority, changefreq };
  return { priority: 0.7, changefreq: 'monthly' };
};

const lastmod = (file) => {
  try {
    const d = execSync(`git log -1 --format=%cs -- "${file}"`, { encoding: 'utf8' }).trim();
    if (d) return d;
  } catch {
    /* untracked or no history yet — fall through */
  }
  return new Date().toISOString().slice(0, 10);
};

const files = execSync("git ls-files -- '*.html'", { encoding: 'utf8' })
  .split('\n')
  .filter(Boolean)
  .filter((f) => !f.startsWith('partials/') && !EXCLUDE.has(f));

const entries = [];
const skipped = [];

for (const file of files) {
  const html = readFileSync(file, 'utf8');

  const robots = html.match(/<meta\s+name="robots"\s+content="([^"]*)"/i)?.[1] || '';
  if (/noindex/i.test(robots)) {
    skipped.push(`${file} (noindex)`);
    continue;
  }

  const canonical = html.match(/<link\s+rel="canonical"\s+href="([^"]+)"/i)?.[1];
  if (!canonical) {
    console.error(`✖ ${file}: no <link rel="canonical"> — cannot place it in the sitemap`);
    process.exit(1);
  }

  entries.push({ url: canonical, file, ...rank(canonical) });
}

// Sorted by priority so the file reads as an outline of the site, and
// deterministically by URL within a tier so diffs stay small.
entries.sort((a, b) => b.priority - a.priority || a.url.localeCompare(b.url));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/build-sitemap.mjs — do not edit by hand.
     Run: npm run build:sitemap -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map(
    (e) => `  <url>
    <loc>${e.url}</loc>
    <lastmod>${lastmod(e.file)}</lastmod>
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority.toFixed(2)}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`;

const before = (() => {
  try {
    return readFileSync('sitemap.xml', 'utf8');
  } catch {
    return '';
  }
})();

writeFileSync('sitemap.xml', xml);
console.log(
  `${before === xml ? '✔ sitemap.xml unchanged' : '✔ wrote sitemap.xml'} — ${entries.length} URLs` +
    (skipped.length ? `, ${skipped.length} skipped (${skipped.join(', ')})` : '')
);
